export const ACCOUNT = {
	ACCOUNT_DELETE: 'ACCOUNT_DELETE',
	ACCOUNT_LOAD: 'ACCOUNT_LOAD',
	ACCOUNT_LOAD_ALL: 'ACCOUNT_LOAD_ALL',
	ACCOUNT_SAVE_REQUEST: 'ACCOUNT_SAVE_REQUEST',
	ACCOUNT_SAVE_SUCCESS: 'ACCOUNT_SAVE_SUCCESS',
	ACCOUNT_SAVE_ERROR: 'ACCOUNT_SAVE_ERROR',
	ACCOUNT_TYPING: 'ACCOUNT_TYPING',
}
