export const CUSTOMER = {
	CUSTOMER_CLEAR_FORM: 'CUSTOMER_CLEAR_FORM',
	CUSTOMER_DELETE: 'CUSTOMER_DELETE',
	CUSTOMER_LOAD: 'CUSTOMER_LOAD',
	CUSTOMER_LOAD_ALL: 'CUSTOMER_LOAD_ALL',
	CUSTOMER_SAVE_REQUEST: 'CUSTOMER_SAVE_REQUEST',
	CUSTOMER_SAVE_SUCCESS: 'CUSTOMER_SAVE_SUCCESS',
	CUSTOMER_SAVE_ERROR: 'CUSTOMER_SAVE_ERROR',
	CUSTOMER_TYPING: 'CUSTOMER_TYPING',
}
