export const CUSTOMER_NUMBER = {
	CUSTOMER_NUMBER_CLEAR_FORM: 'CUSTOMER_NUMBER_CLEAR_FORM',
	CUSTOMER_NUMBER_DELETE: 'CUSTOMER_NUMBER_DELETE',
	CUSTOMER_NUMBER_LOAD: 'CUSTOMER_NUMBER_LOAD',
	CUSTOMER_NUMBER_LOAD_ALL: 'CUSTOMER_NUMBER_LOAD_ALL',
	CUSTOMER_NUMBER_SAVE_REQUEST: 'CUSTOMER_NUMBER_SAVE_REQUEST',
	CUSTOMER_NUMBER_SAVE_SUCCESS: 'CUSTOMER_NUMBER_SAVE_SUCCESS',
	CUSTOMER_NUMBER_SAVE_ERROR: 'CUSTOMER_NUMBER_SAVE_ERROR',
	CUSTOMER_NUMBER_TYPING: 'CUSTOMER_NUMBER_TYPING',
}
