export const PURCHASE = {
	PURCHASE_CLEAR_FORM: 'PURCHASE_CLEAR_FORM',
	PURCHASE_LOAD: 'PURCHASE_LOAD',
	PURCHASE_LOAD_ALL: 'PURCHASE_LOAD_ALL',
	PURCHASE_SAVE_SUCCESS: 'PURCHASE_SAVE_SUCCESS',
	PURCHASE_SAVE_ERROR: 'PURCHASE_SAVE_ERROR',
	PURCHASE_TYPING: 'PURCHASE_TYPING',
}
